config/routes.rb
Rails.application.routes.draw do

  match 'sales_report' => 'static_pages#sales_report', :via => [:get]
  match 'sales_report_create' => 'static_pages#sales_report_create', :via => [:get]
  match 'daily_sales' => 'static_pages#sales', :via => [:get]
  match 'monthly_sales' => 'static_pages#monthly', :via => [:get]
  match 'dine_in' => 'static_pages#table', :via => [:get]
  match 'takeout' => 'static_pages#takeout', :via => [:get]
  match 'table_one' => 'static_pages#one', :via => [:get]
  match 'table_two' => 'static_pages#two', :via => [:get]
  match 'table_three' => 'static_pages#three', :via => [:get]
  match 'table_four' => 'static_pages#four', :via => [:get]
  match 'table_five' => 'static_pages#five', :via => [:get]
  match 'table_six' => 'static_pages#six', :via => [:get]
  match 'table_seven' => 'static_pages#seven', :via => [:get]

  resources :products
  resources :inventories
  resources :order_slip_items
  resources :order_slips do
    collection do
      get :close
    end
    member do
      post :split
      get :archive
      post :merge
      get :activate
    end

  end

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users do
    collection do
      get 'dashboard'
    end
  end
  authenticated :user do
    root :to => 'users#dashboard', :as => :authenticated_root
  end
  root :to => redirect('/login')

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController	
  skip_authorization_check
	# authorize_resource :class => false

  def sales_report_create
    # @report_date = params[:date]
     @report_date = Date.parse("#{params[:date]['day']}-#{params[:date]['month']}-#{params[:date]['year']}") if params[:date]
    if params[:report_type]["daily"]
      render file: 'static_pages/_sales'
    else params[:report_type]["_monthly"]
      render file: 'static_pages/_monthly'
    end  
    # raise 'got here!'
  end

  def table
  end

  def one
  end

  def two
  end

  def three
  end

  def four
  end

  def five
  end

  def six
  end
  
  def seven
  end

  def takeout
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_monthly.html.haml
.row
  .col-md-12
    .page-header
      %h1 Monthly Sales
      %p
      %h3= "For the month of " + @report_date.strftime("%B")

      - previous_month = 1.month.ago
      = link_to sales_report_create_path('date[day]'=> previous_month.day, 'date[month]'=> previous_month.month, 'date[year]'=> previous_month.year, :report_type=>"monthly"), class: "btn btn-default", "data-toggle" => "tooltip", "data-placement" => "top", title: "Previous Month" do
        %span.glyphicon.glyphicon-chevron-left
        Previous Month

      - next_month = 1.month.from_now
      - if (@report_date.month != Date.current.month)
        = link_to sales_report_create_path('date[day]'=> next_month.day, 'date[month]'=> next_month.month, 'date[year]'=> next_month.year, :report_type=>"monthly"), class: "btn btn-default", "data-toggle" => "tooltip", "data-placement" => "top", title: "Next Month" do
          %span.glyphicon.glyphicon-chevron-right
          Next Month

%table.table.table-condensed.table-hover
  %tr
    %th Specials
    %th Quantity
    %th Item Price
    %th Sold per Item
  - Product.where(:category=>"Special").each do |prod|
    - @total = 0
    - @item_qty = 0
    %tr
      %td= prod.item_name
      - OrderSlip.where("created_at >= ? and created_at < ? and open = ?", @report_date.beginning_of_month, @report_date.end_of_month, false).each do |tab|
        - tab.order_slip_items.each do |tab_item|
          - if (prod.item_name == Product.find(tab_item.product_id).item_name)
            - @item_qty = @item_qty + tab_item.quantity
      %td= @item_qty
      %td= number_with_precision(prod.price, precision: 2)
      - @items_sold = @item_qty * prod.price
      %td= number_with_precision(@items_sold, precision: 2)
    - @total = @total + @items_sold

  %tr
    %th Silog
    %th
    %th
    %th
  - Product.where(:category=>"Silog").each do |prod|
    - @item_qty = 0
    %tr
      %td= prod.item_name
      - OrderSlip.where("created_at >= ? and created_at < ? and open = ?", @report_date.beginning_of_month, @report_date.end_of_month, false).each do |tab|
        - tab.order_slip_items.each do |tab_item|
          - if (prod.item_name == Product.find(tab_item.product_id).item_name)
            - @item_qty = @item_qty + tab_item.quantity
      %td= @item_qty
      %td= number_with_precision(prod.price, precision: 2)
      - @items_sold = @item_qty * prod.price
      %td= number_with_precision(@items_sold, precision: 2)      
    - @total = @total + @items_sold

  %tr
    %th Classic
    %th 
    %th
    %th
  - Product.where(:category=>"Classic").each do |prod|
    - @item_qty = 0
    %tr
      %td= prod.item_name
      - OrderSlip.where("created_at >= ? and created_at < ? and open = ?", @report_date.beginning_of_month, @report_date.end_of_month, false).each do |tab|
        - tab.order_slip_items.each do |tab_item|
          - if (prod.item_name == Product.find(tab_item.product_id).item_name)
            - @item_qty = @item_qty + tab_item.quantity
      %td= @item_qty
      %td= number_with_precision(prod.price, precision: 2)
      - @items_sold = @item_qty * prod.price
      %td= number_with_precision(@items_sold, precision: 2)
    - @total = @total + @items_sold

  %tr
    %th Rice Toppings
    %th 
    %th
    %th
  - Product.where(:category=>"Rice Topping").each do |prod|
    - @item_qty = 0
    %tr
      %td= prod.item_name
      - OrderSlip.where("created_at >= ? and created_at < ? and open = ?", @report_date.beginning_of_month, @report_date.end_of_month, false).each do |tab|
        - tab.order_slip_items.each do |tab_item|
          - if (prod.item_name == Product.find(tab_item.product_id).item_name)
            - @item_qty = @item_qty + tab_item.quantity
      %td= @item_qty
      %td= number_with_precision(prod.price, precision: 2)
      - @items_sold = @item_qty * prod.price
      %td= number_with_precision(@items_sold, precision: 2)
    - @total = @total + @items_sold
  
  %tr
    %th Noodles
    %th 
    %th
    %th
  - Product.where(:category=>"Noodles").each do |prod|
    - @item_qty = 0
    %tr
      %td= prod.item_name
      - OrderSlip.where("created_at >= ? and created_at < ? and open = ?", @report_date.beginning_of_month, @report_date.end_of_month, false).each do |tab|
        - tab.order_slip_items.each do |tab_item|
          - if (prod.item_name == Product.find(tab_item.product_id).item_name)
            - @item_qty = @item_qty + tab_item.quantity
      %td= @item_qty
      %td= number_with_precision(prod.price, precision: 2)
      - @items_sold = @item_qty * prod.price
      %td= number_with_precision(@items_sold, precision: 2)
    - @total = @total + @items_sold

  %tr
    %th Sandwich
    %th 
    %th
    %th
  - Product.where(:category=>"Sandwich").each do |prod|
    - @item_qty = 0
    %tr
      %td= prod.item_name
      - OrderSlip.where("created_at >= ? and created_at < ? and open = ?", @report_date.beginning_of_month, @report_date.end_of_month, false).each do |tab|
        - tab.order_slip_items.each do |tab_item|
          - if (prod.item_name == Product.find(tab_item.product_id).item_name)
            - @item_qty = @item_qty + tab_item.quantity
      %td= @item_qty
      %td= number_with_precision(prod.price, precision: 2)
      - @items_sold = @item_qty * prod.price
      %td= number_with_precision(@items_sold, precision: 2)            
    - @total = @total + @items_sold

  %tr
    %th Drink
    %th 
    %th
    %th
  - Product.where(:category=>"Drink").each do |prod|
    - @item_qty = 0
    %tr
      %td= prod.item_name
      - OrderSlip.where("created_at >= ? and created_at < ? and open = ?", @report_date.beginning_of_month, @report_date.end_of_month, false).each do |tab|
        - tab.order_slip_items.each do |tab_item|
          - if (prod.item_name == Product.find(tab_item.product_id).item_name)
            - @item_qty = @item_qty + tab_item.quantity
      %td= @item_qty
      %td= number_with_precision(prod.price, precision: 2)
      - @items_sold = @item_qty * prod.price
      %td= number_with_precision(@items_sold, precision: 2)
    - @total = @total + @items_sold

  %tr
    %th Cigarettes
    %th 
    %th
    %th
  - Product.where(:category=>"Cigarettes").each do |prod|
    - @item_qty = 0
    %tr
      %td= prod.item_name
      - OrderSlip.where("created_at >= ? and created_at < ? and open = ?", @report_date.beginning_of_month, @report_date.end_of_month, false).each do |tab|
        - tab.order_slip_items.each do |tab_item|
          - if (prod.item_name == Product.find(tab_item.product_id).item_name)
            - @item_qty = @item_qty + tab_item.quantity
      %td= @item_qty
      %td= number_with_precision(prod.price, precision: 2)
      - @items_sold = @item_qty * prod.price
      %td= number_with_precision(@items_sold, precision: 2)
    - @total = @total + @items_sold
 
  %tr
    %th.h3 Total Sales
    %td
    %td
    %td.h3= @total

app/views/static_pages/five.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Table 5
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Add order_slip" do
          %span.glyphicon.glyphicon-plus
        = link_to order_slips_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Order Slips index" do
          %span.glyphicon.glyphicon-list

  .row
    .col-md-12
      - OrderSlip.all.each do |slip|
        %table.table.table-striped.table-condensed
          - if (slip.table_number.starts_with? '5' and slip.open?)
            %tr
              %th Date:
              %td= slip.created_at.strftime("%d %b %y")
            %tr
              %th Order Type:
              %td= slip.order_type
            %tr
              %th Server:
              %td= User.find(slip.user_id).name 
            - @total = 0
            .panel.panel-default
              .panel-heading Item Details
              %table.table.table-striped.table-condensed
                %tr
                  %th Timestamp
                  %th Name
                  %th Quantity
                  %th Item Price
                  %th Total Price
                - slip.order_slip_items.each do |i|
                  %tr
                    %td= i.created_at.strftime("%I:%M %p")
                    %td= Product.find(i.product_id).item_name
                    %td= i.quantity
                    %td= number_with_precision(Product.find(i.product_id).price, precision: 2)
                    - @per_item = (i.quantity * Product.find(i.product_id).price)
                    %td= number_with_precision(@per_item, precision: 2)
                    - @total = @total + @per_item
                - if (slip.takeout_type == "Box")
                  %tr
                    %td Takeout Box:
                    %td
                    %td
                    %td
                    %td 5.00
                    -@total = @total + 5
                %tr
                  %td Total:
                  %td
                  %td
                  %td
                  %td= number_with_precision(@total, precision: 2)

app/views/static_pages/four.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Table 4
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Add order_slip" do
          %span.glyphicon.glyphicon-plus
        = link_to order_slips_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Order Slips index" do
          %span.glyphicon.glyphicon-list

  .row
    .col-md-12
      - OrderSlip.all.each do |slip|
        %table.table.table-striped.table-condensed
          - if (slip.table_number.starts_with? '4' and slip.open?)
            %tr
              %th Date:
              %td= slip.created_at.strftime("%d %b %y")
            %tr
              %th Order Type:
              %td= slip.order_type
            %tr
              %th Server:
              %td= User.find(slip.user_id).name 
            - @total = 0
            .panel.panel-default
              .panel-heading Item Details
              %table.table.table-striped.table-condensed
                %tr
                  %th Timestamp
                  %th Name
                  %th Quantity
                  %th Item Price
                  %th Total Price
                - slip.order_slip_items.each do |i|
                  %tr
                    %td= i.created_at.strftime("%I:%M %p")
                    %td= Product.find(i.product_id).item_name
                    %td= i.quantity
                    %td= number_with_precision(Product.find(i.product_id).price, precision: 2)
                    - @per_item = (i.quantity * Product.find(i.product_id).price)
                    %td= number_with_precision(@per_item, precision: 2)
                    - @total = @total + @per_item
                - if (slip.takeout_type == "Box")
                  %tr
                    %td Takeout Box:
                    %td
                    %td
                    %td
                    %td 5.00
                    -@total = @total + 5
                %tr
                  %td Total:
                  %td
                  %td
                  %td
                  %td= number_with_precision(@total, precision: 2)

app/views/static_pages/one.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Table 1
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Add order_slip" do
          %span.glyphicon.glyphicon-plus
        = link_to order_slips_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Order Slips index" do
          %span.glyphicon.glyphicon-list

  .row
    .col-md-12
      - OrderSlip.all.each do |slip|
        %table.table.table-striped.table-condensed
          - if (slip.table_number.starts_with? '1' and slip.open?)
            %tr
              %th Date:
              %td= slip.created_at.strftime("%d %b %y")
            %tr
              %th Order Type:
              %td= slip.order_type
            %tr
              %th Server:
              %td= User.find(slip.user_id).name 
            - @total = 0
            .panel.panel-default
              .panel-heading Item Details
              %table.table.table-striped.table-condensed
                %tr
                  %th Timestamp
                  %th Name
                  %th Quantity
                  %th Item Price
                  %th Total Price
                - slip.order_slip_items.each do |i|
                  %tr
                    %td= i.created_at.strftime("%I:%M %p")
                    %td= Product.find(i.product_id).item_name
                    %td= i.quantity
                    %td= number_with_precision(Product.find(i.product_id).price, precision: 2)
                    - @per_item = (i.quantity * Product.find(i.product_id).price)
                    %td= number_with_precision(@per_item, precision: 2)
                    - @total = @total + @per_item
                - if (slip.takeout_type == "Box")
                  %tr
                    %td Takeout Box:
                    %td
                    %td
                    %td
                    %td 5.00
                    -@total = @total + 5
                %tr
                  %td Total:
                  %td
                  %td
                  %td
                  %td= number_with_precision(@total, precision: 2)

app/views/static_pages/sales_report.html.haml
.row
  .col-md-12
    .page-header
      %h1 Sales

.row
  .col-md-12
    %table.table.table-condensed.table-hover
      = form_tag(sales_report_create_path, :method=>'get') do
        .form-group
          %tr
            %th= label :report_date, "Report Date: "
            %td= select_date(date = Date.today, options = {}, html_options = {})
          %tr
            %th= label :report_type, "Report Type: "
          %tr
            %th= label :daily, "Daily"
            %td= radio_button_tag "report_type", "daily", checked=true
          %tr
            %th= label :monthly, "Monthly"
            %td= radio_button_tag "report_type", "monthly"

        .form-group
          %tr
            %td= submit_tag 'Generate Sales Report', class: "btn btn-primary btn-xs"

app/views/static_pages/seven.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Table 7
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Add order_slip" do
          %span.glyphicon.glyphicon-plus
        = link_to order_slips_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Order Slips index" do
          %span.glyphicon.glyphicon-list

  .row
    .col-md-12
      - OrderSlip.all.each do |slip|
        %table.table.table-striped.table-condensed
          - if (slip.table_number.starts_with? '7' and slip.open?)
            %tr
              %th Date:
              %td= slip.created_at.strftime("%d %b %y")
            %tr
              %th Order Type:
              %td= slip.order_type
            %tr
              %th Server:
              %td= User.find(slip.user_id).name 
            - @total = 0
            .panel.panel-default
              .panel-heading Item Details
              %table.table.table-striped.table-condensed
                %tr
                  %th Timestamp
                  %th Name
                  %th Quantity
                  %th Item Price
                  %th Total Price
                - slip.order_slip_items.each do |i|
                  %tr
                    %td= i.created_at.strftime("%I:%M %p")
                    %td= Product.find(i.product_id).item_name
                    %td= i.quantity
                    %td= number_with_precision(Product.find(i.product_id).price, precision: 2)
                    - @per_item = (i.quantity * Product.find(i.product_id).price)
                    %td= number_with_precision(@per_item, precision: 2)
                    - @total = @total + @per_item
                - if (slip.takeout_type == "Box")
                  %tr
                    %td Takeout Box:
                    %td
                    %td
                    %td
                    %td 5.00
                    -@total = @total + 5
                %tr
                  %td Total:
                  %td
                  %td
                  %td
                  %td= number_with_precision(@total, precision: 2)

app/views/static_pages/table.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Dine-In
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "New Order Slip" do
          %span.glyphicon.glyphicon-plus
    %table.table.table-condensed.table-bordered
      %tr
        %td= link_to image_tag('t4 copy.png', width: '100', height: '100'), table_four_path
        %td= link_to image_tag('t5 copy.png', width: '100', height: '100'), table_five_path
      //   %td= link_to image_tag('t4 copy.png', width: '100', height: '100'), OrderSlip.where('table_number LIKE ?', '4')
      //   %td= link_to image_tag('t5 copy.png', width: '100', height: '100'), OrderSlip.where('table_number LIKE ?', '5')
      %tr  
        %td= link_to image_tag('t3 copy.png', width: '100', height: '100'), table_three_path
        %td= link_to image_tag('t6 copy.png', width: '100', height: '100'), table_six_path
      //   %td= link_to image_tag('t3 copy.png', width: '100', height: '100'), OrderSlip.where('table_number LIKE ?', '3')
      //   %td= link_to image_tag('t6 copy.png', width: '100', height: '100'), OrderSlip.where('table_number LIKE ?', '6')
      %tr
        %td= link_to image_tag('t2 copy.png', width: '100', height: '100'), table_two_path
        %td= link_to image_tag('t7 copy.png', width: '100', height: '100'), table_seven_path
      //   %td= link_to image_tag('t2 copy.png', width: '100', height: '100'), OrderSlip.where('table_number LIKE ?', '2')
      //   %td= link_to image_tag('t7 copy.png', width: '100', height: '100'), OrderSlip.where('table_number LIKE ?', '7')
      %tr
        %td= link_to image_tag('t1 copy.png', width: '100', height: '100'), table_one_path
      //   %td= link_to image_tag('t1 copy.png', width: '100', height: '100'), OrderSlip.where('table_number LIKE ?', '1')

app/views/static_pages/takeout.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Takeout
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "New Order Slip" do
          %span.glyphicon.glyphicon-plus
.row
  .col-md-12
    %table.table.table-condensed.table-hover
      %tr
        %th Takeout Number
        %th Type
        %th
      - OrderSlip.where(:order_type => "Takeout").each do |order_slip|
        %tr
          %td= order_slip.takeout_number
          %td= order_slip.takeout_type
          %td
            .btn-group.btn-group-xs
              = link_to order_slip, class: 'btn btn-primary' do
                %span.glyphicon.glyphicon-eye-open
                View              
              %button.btn.btn-primary.dropdown-toggle{'type' => 'button', 'data-toggle' => 'dropdown'}
                %span.caret
                %span.sr-only Toggle Dropdown
              %ul.dropdown-menu{role: 'menu'}
                %li
                  = link_to edit_order_slip_path(order_slip) do
                    %span.glyphicon.glyphicon-edit
                    Edit
                %li
                  = link_to order_slip, :method => :delete, :data => { :confirm => 'Are you sure?' } do
                    %span.glyphicon.glyphicon-trash
                    Destroy
    =# paginate @order_slips, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

app/views/static_pages/three.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Table 3
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Add order_slip" do
          %span.glyphicon.glyphicon-plus
        = link_to order_slips_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Order Slips index" do
          %span.glyphicon.glyphicon-list

  .row
    .col-md-12
      - OrderSlip.all.each do |slip|
        %table.table.table-striped.table-condensed
          - if (slip.table_number.starts_with? '3' and slip.open?)
            %tr
              %th Date:
              %td= slip.created_at.strftime("%d %b %y")
            %tr
              %th Order Type:
              %td= slip.order_type
            %tr
              %th Server:
              %td= User.find(slip.user_id).name 
            - @total = 0
            .panel.panel-default
              .panel-heading Item Details
              %table.table.table-striped.table-condensed
                %tr
                  %th Timestamp
                  %th Name
                  %th Quantity
                  %th Item Price
                  %th Total Price
                - slip.order_slip_items.each do |i|
                  %tr
                    %td= i.created_at.strftime("%I:%M %p")
                    %td= Product.find(i.product_id).item_name
                    %td= i.quantity
                    %td= number_with_precision(Product.find(i.product_id).price, precision: 2)
                    - @per_item = (i.quantity * Product.find(i.product_id).price)
                    %td= number_with_precision(@per_item, precision: 2)
                    - @total = @total + @per_item
                - if (slip.takeout_type == "Box")
                  %tr
                    %td Takeout Box:
                    %td
                    %td
                    %td
                    %td 5.00
                    -@total = @total + 5
                %tr
                  %td Total:
                  %td
                  %td
                  %td
                  %td= number_with_precision(@total, precision: 2)

app/views/static_pages/two.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Table 2
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Add order_slip" do
          %span.glyphicon.glyphicon-plus
        = link_to order_slips_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Order Slips index" do
          %span.glyphicon.glyphicon-list

  .row
    .col-md-12
      - OrderSlip.all.each do |slip|
        %table.table.table-striped.table-condensed
          - if (slip.table_number.starts_with? '2' and slip.open?)
            %tr
              %th Date:
              %td= slip.created_at.strftime("%d %b %y")
            %tr
              %th Order Type:
              %td= slip.order_type
            %tr
              %th Server:
              %td= User.find(slip.user_id).name 
            - @total = 0
            .panel.panel-default
              .panel-heading Item Details
              %table.table.table-striped.table-condensed
                %tr
                  %th Timestamp
                  %th Name
                  %th Quantity
                  %th Item Price
                  %th Total Price
                - slip.order_slip_items.each do |i|
                  %tr
                    %td= i.created_at.strftime("%I:%M %p")
                    %td= Product.find(i.product_id).item_name
                    %td= i.quantity
                    %td= number_with_precision(Product.find(i.product_id).price, precision: 2)
                    - @per_item = (i.quantity * Product.find(i.product_id).price)
                    %td= number_with_precision(@per_item, precision: 2)
                    - @total = @total + @per_item
                - if (slip.takeout_type == "Box")
                  %tr
                    %td Takeout Box:
                    %td
                    %td
                    %td
                    %td 5.00
                    -@total = @total + 5
                %tr
                  %td Total:
                  %td
                  %td
                  %td
                  %td= number_with_precision(@total, precision: 2)