config/routes.rb
Rails.application.routes.draw do

  match 'sales_report' => 'static_pages#sales_report', :via => [:get]
  match 'sales_report_create' => 'static_pages#sales_report_create', :via => [:get]
  match 'daily_sales' => 'static_pages#sales', :via => [:get]
  match 'monthly_sales' => 'static_pages#monthly', :via => [:get]
  match 'dine_in' => 'static_pages#table', :via => [:get]
  match 'takeout' => 'static_pages#takeout', :via => [:get]
  match 'table_one' => 'static_pages#one', :via => [:get]
  match 'table_two' => 'static_pages#two', :via => [:get]
  match 'table_three' => 'static_pages#three', :via => [:get]
  match 'table_four' => 'static_pages#four', :via => [:get]
  match 'table_five' => 'static_pages#five', :via => [:get]
  match 'table_six' => 'static_pages#six', :via => [:get]
  match 'table_seven' => 'static_pages#seven', :via => [:get]

  resources :products
  resources :inventories
  resources :order_slip_items
  resources :order_slips do
    collection do
      get :close
    end
    member do
      post :split
      get :archive
      post :merge
      get :activate
    end

  end

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users do
    collection do
      get 'dashboard'
    end
  end
  authenticated :user do
    root :to => 'users#dashboard', :as => :authenticated_root
  end
  root :to => redirect('/login')

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/order_slip_item.rb
class OrderSlipItem < ActiveRecord::Base
	has_many :products

	belongs_to :order_slip

	validates :quantity,  :numericality => { :greater_than => 0 }, presence: true
end

app/controllers/order_slip_items_controller.rb
class OrderSlipItemsController < ApplicationController
  before_action :set_order_slip_item, only: [:show, :edit, :update, :destroy]
  before_action :set_index, only: [:index]
  before_action :build_order_slip_item, only: [:create]
  load_and_authorize_resource

  # GET /order_slip_items
  def index
  end

  # GET /order_slip_items/1
  def show
  end

  # GET /order_slip_items/new
  def new
  end

  # GET /order_slip_items/1/edit
  def edit
  end

  # POST /order_slip_items
  def create
    if @order_slip_item.save
      product = Product.find(@order_slip_item.product_id)
      prod_item = product.item_name
      if (product.category == "Silog")
        prod_item.slice!("silog")
      end
      inv_item = Inventory.find_by_item_name(prod_item)
      inv_item.quantity = inv_item.quantity - @order_slip_item.quantity
        inv_item.update_attribute(:quantity, inv_item.quantity)
      redirect_to @order_slip_item, notice: 'Order slip item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /order_slip_items/1
  def update
      product = Product.find(@order_slip_item.product_id)
      prod_item = product.item_name
      if (product.category == "Silog")
        prod_item.slice!("silog")
      end
      inv_item = Inventory.find_by_item_name(prod_item)
      inv_item.quantity = inv_item.quantity + @order_slip_item.quantity
      inv_item.update_attribute(:quantity, inv_item.quantity)
    if @order_slip_item.update(order_slip_item_params)
      redirect_to @order_slip_item, notice: 'Order slip item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /order_slip_items/1
  def destroy
    @order_slip_item.destroy
    redirect_to order_slip_items_url, notice: 'Order slip item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_slip_item
      @order_slip_item = OrderSlipItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_slip_item_params
      params.require(:order_slip_item).permit(:quantity, :product_id)
    end

    # sanitize search parameters, consider implementing the ransackable methods
    def order_slip_item_search_params
      params[:q].assert_valid_keys('s', 'quantity_cont') unless params[:q].blank?
      params[:q]
    end
    
    def set_index
      @q = OrderSlipItem.search(order_slip_item_search_params, auth_object: current_user)
      @order_slip_items = @q.result(distinct: true).accessible_by(current_ability).page params[:page]
    end
    
    def build_order_slip_item
      @order_slip_item = OrderSlipItem.new(order_slip_item_params)
    end
end

app/helpers/order_slip_items_helper.rb
module OrderSlipItemsHelper
end

app/views/order_slip_items/_form.html.haml
= simple_form_for @order_slip_item, html:{class: 'form-horizontal', role: 'form'} do |f|
  = form_error_notification(f)
  = f.input :quantity
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit

app/views/order_slip_items/edit.html.haml
.row
  .col-md-12
    %h1
      Editing order_slip_item
      = link_to @order_slip_item, class: "btn btn-warning btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Discard changes" do
        %span.glyphicon.glyphicon-refresh
      = link_to order_slip_items_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Order Slip Items index" do
        %span.glyphicon.glyphicon-list
.row
  .col-md-12
    = render 'form'

app/views/order_slip_items/index.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Order Slip Items Index
        = link_to new_order_slip_item_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Add order_slip_item" do
          %span.glyphicon.glyphicon-plus
.row
  .col-md-12
    .well
      = search_form_for @q, html:{class: 'form-inline', role: 'form'} do |f|
        %kbd Search
        .form-group
          = f.label :quantity_cont, class: 'sr-only'
          = f.input_field :quantity_cont, as: 'string', placeholder: 'Quantity'
        = button_tag class: 'btn btn-default' do
          %span.glyphicon.glyphicon-search
        = link_to 'Clear', request.path
    %table.table.table-condensed.table-hover
      %tr
        %th= sort_link(@q, :quantity)
        %th
      - @order_slip_items.each do |order_slip_item|
        %tr
          %td= order_slip_item.quantity
          %td
            .btn-group.btn-group-xs
              = link_to order_slip_item, class: 'btn btn-primary' do
                %span.glyphicon.glyphicon-eye-open
                View              
              %button.btn.btn-primary.dropdown-toggle{'type' => 'button', 'data-toggle' => 'dropdown'}
                %span.caret
                %span.sr-only Toggle Dropdown
              %ul.dropdown-menu{role: 'menu'}
                %li
                  = link_to edit_order_slip_item_path(order_slip_item) do
                    %span.glyphicon.glyphicon-edit
                    Edit
                %li
                  = link_to order_slip_item, :method => :delete, :data => { :confirm => 'Are you sure?' } do
                    %span.glyphicon.glyphicon-trash
                    Destroy
    = paginate @order_slip_items, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

app/views/order_slip_items/new.html.haml
.row
  .col-md-12
    %h1
      New order_slip_item
      = link_to order_slip_items_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Order Slip Items index" do
        %span.glyphicon.glyphicon-list
.row
  .col-md-12
    = render 'form'

app/views/order_slip_items/show.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Order Slip Item Detail
        = link_to edit_order_slip_item_path(@order_slip_item), class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Edit order_slip_item" do
          %span.glyphicon.glyphicon-edit
        = link_to order_slip_items_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Order Slip Items index" do
          %span.glyphicon.glyphicon-list
.row
  .col-md-2
    <strong>Quantity:</strong>
  .col-md-10
    = @order_slip_item.quantity