config/routes.rb
Rails.application.routes.draw do

  match 'sales_report' => 'static_pages#sales_report', :via => [:get]
  match 'sales_report_create' => 'static_pages#sales_report_create', :via => [:get]
  match 'daily_sales' => 'static_pages#sales', :via => [:get]
  match 'monthly_sales' => 'static_pages#monthly', :via => [:get]
  match 'dine_in' => 'static_pages#table', :via => [:get]
  match 'takeout' => 'static_pages#takeout', :via => [:get]
  match 'table_one' => 'static_pages#one', :via => [:get]
  match 'table_two' => 'static_pages#two', :via => [:get]
  match 'table_three' => 'static_pages#three', :via => [:get]
  match 'table_four' => 'static_pages#four', :via => [:get]
  match 'table_five' => 'static_pages#five', :via => [:get]
  match 'table_six' => 'static_pages#six', :via => [:get]
  match 'table_seven' => 'static_pages#seven', :via => [:get]

  resources :products
  resources :inventories
  resources :order_slip_items
  resources :order_slips do
    collection do
      get :close
    end
    member do
      post :split
      get :archive
      post :merge
      get :activate
    end

  end

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users do
    collection do
      get 'dashboard'
    end
  end
  authenticated :user do
    root :to => 'users#dashboard', :as => :authenticated_root
  end
  root :to => redirect('/login')

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/order_slip.rb
class OrderSlip < ActiveRecord::Base
	has_many :order_slip_items, :dependent => :destroy
	accepts_nested_attributes_for :order_slip_items, allow_destroy: true, reject_if: lambda { |a| a[:product_id].blank? or a[:quantity].blank? }

	TYPES = ["Dine-In", "Takeout"]

	TABLES = ["1", "2", "3", "4", "5", "6", "7"]

	TAKEOUTS = ["Plastic", "Box"]

	validates :order_type, presence: true
	validates :table_number, uniqueness: true, if: Proc.new {|order_slip| order_slip.open? and order_slip.order_type=="Dine-In"}
	validates :takeout_number, uniqueness: true, if: Proc.new {|order_slip| order_slip.open? and order_slip.order_type=="Takeout"}


end

app/controllers/order_slips_controller.rb
class OrderSlipsController < ApplicationController
  before_action :set_order_slip, only: [:show, :edit, :update, :destroy]
  before_action :set_index, only: [:index]
  before_action :build_order_slip, only: [:create]
  load_and_authorize_resource

  # GET /order_slips
  def index
  end

  def close
    @q = OrderSlip.search(params[:q])
    @order_slips = @q.result.where(:open=>false).page(params[:page]).per(50)
    # @order_slips = OrderSlip.where(:open => false).all
  end

  # GET /order_slips/1
  def show
  end

  # GET /order_slips/new
  def new
    @order_slip.order_slip_items.build
  end

  # GET /order_slips/1/edit
  def edit
    @order_slip.order_slip_items.build
  end

  # POST /order_slips
  def create
    if @order_slip.save
      redirect_to @order_slip, notice: 'Order slip was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /order_slips/1
  def update
    if @order_slip.update(order_slip_params)
      redirect_to @order_slip, notice: 'Order slip was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /order_slips/1
  def destroy
    @order_slip.order_slip_items.each do |osi|
        product = Product.find(osi.product_id)
        prod_item = product.item_name
        if (product.category == "Silog")
          prod_item.slice!("silog")
        end
        inv_item = Inventory.find_by_item_name(prod_item)
        inv_item.quantity = inv_item.quantity + osi.quantity
        inv_item.update_attribute(:quantity, inv_item.quantity)
    end
    @order_slip.destroy
    redirect_to order_slips_url, notice: 'Order slip was successfully destroyed.'
  end

  def archive
    @order_slip.order_slip_items.each do |osi|
      product = Product.find(osi.product_id)
      prod_item = product.item_name
      if (product.category == "Silog")
        prod_item.slice!("silog")
      end
      inv_item = Inventory.find_by_item_name(prod_item)
      inv_item.quantity = inv_item.quantity - osi.quantity
      inv_item.update_attribute(:quantity, inv_item.quantity)
    end
    @order_slip.update_attribute(:open, false)

    redirect_to order_slips_url, notice: 'Order slip was successfully closed.'
  end

  def activate
    @order_slip.update_attribute(:open, true)
    redirect_to @order_slip, notice: 'Order slip was successfully opened.'
  end

  def split
    letters = ('A'..'Z').to_a
    @order_slip = OrderSlip.find(params[:id])
    if @order_slip.takeout_number.empty?
      @new_os = OrderSlip.create!(:order_date=>@order_slip.order_date, :order_type=>@order_slip.order_type, :table_number=>@order_slip.table_number+letters.shift, :user_id=>@order_slip.user_id, :open=> @order_slip.open)
      params[:selected].each do |i|
        @new_os.order_slip_items << OrderSlipItem.find(i)
      end
      @new_os.save!
    elsif @order_slip.table_number.empty?
      @new_os = OrderSlip.create!(:order_date=>@order_slip.order_date, :order_type=>@order_slip.order_type, :takeout_number=>@order_slip.takeout_number+letters.shift, :user_id=>@order_slip.user_id, :open=> @order_slip.open)
      params[:selected].each do |i|
        @new_os.order_slip_items << OrderSlipItem.find(i)
      end
      @new_os.save!
    end
    
    redirect_to @new_os, notice: 'Order slip was successfully split.'
  end

  def merge
    @order_slip = OrderSlip.find(params[:id])
    tab = OrderSlip.find(params[:another_id])
    tab.order_slip_items.each do |i|
      @order_slip.order_slip_items.create(:quantity=>i.quantity, :order_slip_id=>@order_slip.id, :product_id=>i.product_id)
    end
    tab.destroy
    redirect_to @order_slip, notice: 'Order slips were successfully merged.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_slip
      @order_slip = OrderSlip.find(params[:id])
    end
 
    # Only allow a trusted parameter "white list" through.
    def order_slip_params
      params.require(:order_slip).permit(:order_type, :table_number, :takeout_number, :takeout_type, :user_id, :open, :created_at, :updated_at,
        order_slip_items_attributes: [:id, :product_id, :quantity, :_destroy])
    end

    # sanitize search parameters, consider implementing the ransackable methods
    def order_slip_search_params
      params[:q].assert_valid_keys('s', 'order_type_cont', 'table_number_cont', 'takeout_number_cont', 'takeout_type_cont', 'user_id_cont', 'open') unless params[:q].blank?
      params[:q]
    end
    
    def set_index
      @q = OrderSlip.search(order_slip_search_params, auth_object: current_user)
      @order_slips = @q.result(distinct: true).accessible_by(current_ability).page params[:page]
    end

    def build_order_slip
      @order_slip = OrderSlip.new(order_slip_params)
    end
end

app/helpers/order_slips_helper.rb
module OrderSlipsHelper
end

app/views/order_slips/_form.html.haml
= simple_nested_form_for @order_slip, html:{class: 'form-horizontal', role: 'form'} do |f|
  = form_error_notification(f)
  .col-md-5
    = f.input :open#, as: :hidden, input_html: {value: true}
    = f.input :order_type, collection: OrderSlip::TYPES, as: :radio_buttons
    = f.input :table_number, collection: OrderSlip::TABLES
    = f.input :takeout_number
    = f.input :takeout_type, collection: OrderSlip::TAKEOUTS
    = f.input :user_id, collection: User.where(:status => "active").order("first_name asc").all, label_method: "name", label: "Server"
  .col-md-7
    = f.simple_fields_for :order_slip_items do |i|
      .row
        .col-md-6
          = i.input :product_id, collection: Product.order("item_name asc").all, label_method: "item_name", label: "Item Name"
        .col-md-5
          = i.input :quantity, :input_html => { min: 0 }
        .col-md-1
          = i.link_to_remove "", class: "glyphicon glyphicon-remove btn btn-primary"
    = f.link_to_add "", :order_slip_items, class: "glyphicon glyphicon-plus btn btn-primary btn-xs"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit

app/views/order_slips/archive.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Closed Slips Index
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "New Order Slip" do
          %span.glyphicon.glyphicon-plus

    %table.table.table-condensed.table-hover
      %tr
        %th Status
        %th Order Type
        %th Table Number
        %th Takeout Number
        %th Takeout Type
        %th Server
        %th
      - @order_slips.each do |order_slip|
        %tr
          -if !(order_slip.open?)
            %td Closed
            %td= order_slip.order_type
            %td= order_slip.table_number
            %td= order_slip.takeout_number
            %td= order_slip.takeout_type
            %td= User.find(order_slip.user_id).name
            %td
              .btn-group.btn-group-xs
                = link_to order_slip, class: 'btn btn-primary' do
                  %span.glyphicon.glyphicon-eye-open
                  View              
                %button.btn.btn-primary.dropdown-toggle{'type' => 'button', 'data-toggle' => 'dropdown'}
                  %span.caret
                  %span.sr-only Toggle Dropdown
                %ul.dropdown-menu{role: 'menu'}
                  %li
                    = link_to edit_order_slip_path(order_slip) do
                      %span.glyphicon.glyphicon-edit
                      Edit
                  %li
                    = link_to archive_order_slip_path(order_slip), :method => :post do
                      %span.glyphicon.glyphicon-check
                      Close
                  %li.divider
                  %li
                    = link_to order_slip, :method => :delete, :data => { :confirm => 'Are you sure?' } do
                      %span.glyphicon.glyphicon-trash
                      Cancel

    = paginate @order_slips, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

app/views/order_slips/close.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Closed Order Slips
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "New Order Slip" do
          %span.glyphicon.glyphicon-plus
.row
  .col-md-12
    .well
      = search_form_for @q, html:{class: 'form-inline', role: 'form'} do |f|
        %kbd Search
        .form-group
          = f.label :order_type_cont, class: 'sr-only'
          = f.input_field :order_type_cont, as: 'string', placeholder: 'Order type'
        .form-group
          = f.label :table_number_cont, class: 'sr-only'
          = f.input_field :table_number_cont, as: 'string', placeholder: 'Table number'
        .form-group
          = f.label :takeout_number_cont, class: 'sr-only'
          = f.input_field :takeout_number_cont, as: 'string', placeholder: 'Takeout number'
        .form-group
          = f.label :takeout_type_cont, class: 'sr-only'
          = f.input_field :takeout_type_cont, as: 'string', placeholder: 'Takeout Type'
        .form-group
          = f.label :user_id_cont, class: 'sr-only'
          = f.input_field :user_id_cont, as: 'string', placeholder: 'Waiter'
        = button_tag class: 'btn btn-default' do
          %span.glyphicon.glyphicon-search
        = link_to 'Clear', request.path
    %table.table.table-condensed.table-hover
      %tr
        %th Status
        %th= sort_link(@q, :order_type)
        %th= sort_link(@q, :table_number)
        %th= sort_link(@q, :takeout_number)
        %th= sort_link(@q, :takeout_type)
        %th= sort_link(@q, :user_id)
        %th
      - @order_slips.each do |order_slip|
        %tr
          -if order_slip.open?
            %td Open
          - else
            %td Closed 
          %td= order_slip.order_type
          %td= order_slip.table_number
          %td= order_slip.takeout_number
          %td= order_slip.takeout_type
          %td= User.find(order_slip.user_id).name
          %td
            .btn-group.btn-group-xs
              = link_to order_slip, class: 'btn btn-primary' do
                %span.glyphicon.glyphicon-eye-open
                View              
              %button.btn.btn-primary.dropdown-toggle{'type' => 'button', 'data-toggle' => 'dropdown'}
                %span.caret
                %span.sr-only Toggle Dropdown
              %ul.dropdown-menu{role: 'menu'}
                %li
                  = link_to edit_order_slip_path(order_slip) do
                    %span.glyphicon.glyphicon-edit
                    Edit
                - if !(order_slip.open?)    
                  %li
                    = link_to activate_order_slip_path(order_slip) do
                      %span.glyphicon.glyphicon-check
                      Open  
                - if (order_slip.open?)
                  %li.divider
                  %li
                    = link_to order_slip, :method => :delete, :data => { :confirm => 'Are you sure?' } do
                      %span.glyphicon.glyphicon-trash
                      Cancel

    = paginate @order_slips, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

app/views/order_slips/edit.html.haml
.row
  .col-md-12
    %h1
      Editing Order Slip
      = link_to @order_slip, class: "btn btn-warning btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Discard changes" do
        %span.glyphicon.glyphicon-refresh
      = link_to order_slips_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "All Order Slips" do
        %span.glyphicon.glyphicon-list
.row
  .col-md-12
    = render 'form'

app/views/order_slips/index.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Order Slips Index
        = link_to new_order_slip_path, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "New Order Slip" do
          %span.glyphicon.glyphicon-plus
.row
  .col-md-12
    .well
      = search_form_for @q, html:{class: 'form-inline', role: 'form'} do |f|
        %kbd Search
        .form-group
          = f.label :order_type_cont, class: 'sr-only'
          = f.input_field :order_type_cont, as: 'string', placeholder: 'Order type'
        .form-group
          = f.label :table_number_cont, class: 'sr-only'
          = f.input_field :table_number_cont, as: 'string', placeholder: 'Table number'
        .form-group
          = f.label :takeout_number_cont, class: 'sr-only'
          = f.input_field :takeout_number_cont, as: 'string', placeholder: 'Takeout number'
        .form-group
          = f.label :takeout_type_cont, class: 'sr-only'
          = f.input_field :takeout_type_cont, as: 'string', placeholder: 'Takeout Type'
        .form-group
          = f.label :user_id_cont, class: 'sr-only'
          = f.input_field :user_id_cont, as: 'string', placeholder: 'Waiter'
        = button_tag class: 'btn btn-default' do
          %span.glyphicon.glyphicon-search
        = link_to 'Clear', request.path
    %table.table.table-condensed.table-hover
      %tr
        %th Status
        %th= sort_link(@q, :order_type)
        %th= sort_link(@q, :table_number)
        %th= sort_link(@q, :takeout_number)
        %th= sort_link(@q, :takeout_type)
        %th= sort_link(@q, :user_id)
        %th
      - @order_slips.each do |order_slip|
        %tr
          -if order_slip.open?
            %td Open
            %td= order_slip.order_type
            %td= order_slip.table_number
            %td= order_slip.takeout_number
            %td= order_slip.takeout_type
            %td= User.find(order_slip.user_id).name
            %td
              .btn-group.btn-group-xs
                = link_to order_slip, class: 'btn btn-primary' do
                  %span.glyphicon.glyphicon-eye-open
                  View              
                %button.btn.btn-primary.dropdown-toggle{'type' => 'button', 'data-toggle' => 'dropdown'}
                  %span.caret
                  %span.sr-only Toggle Dropdown
                %ul.dropdown-menu{role: 'menu'}
                  %li
                    = link_to edit_order_slip_path(order_slip) do
                      %span.glyphicon.glyphicon-edit
                      Edit
                  - if (order_slip.open?)    
                    %li
                      = link_to archive_order_slip_path(order_slip), :method => :get, :data => { :confirm => 'Bill Out?' }  do
                        %span.glyphicon.glyphicon-check
                        Close  
                  - if (order_slip.open?)
                    %li.divider
                    %li
                      = link_to order_slip, :method => :delete, :data => { :confirm => 'Are you sure?' } do
                        %span.glyphicon.glyphicon-trash
                        Cancel

    = paginate @order_slips, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

app/views/order_slips/new.html.haml
.row
  .col-md-12
    %h1
      New Order Slip
      = link_to order_slips_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "All Order Slip" do
        %span.glyphicon.glyphicon-list
.row
  .col-md-12
    = render 'form'

app/views/order_slips/show.html.haml
.row
  .col-md-12
    .page-header
      %h1
        -unless @order_slip.table_number.nil?
          %tr
            %th Table Number:
            %td= @order_slip.table_number
        - unless @order_slip.takeout_number.nil?
          %tr
            %th Takeout Number:
            %td= @order_slip.takeout_number
        = link_to edit_order_slip_path(@order_slip), class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Edit Order Slip" do
          %span.glyphicon.glyphicon-edit
        = link_to order_slips_path, class: "btn btn-default btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "All Order Slips" do
          %span.glyphicon.glyphicon-list
        - if @order_slip.open?
          = link_to archive_order_slip_path(@order_slip), class: "btn btn-danger", "data-toggle" => "tooltip", "data-placement" => "top", title: "Close" do
            Close
        - if !(@order_slip.open?)    
          = link_to activate_order_slip_path(@order_slip), class: "btn btn-success", "data-toggle" => "tooltip", "data-placement" => "top", title: "Open" do
            Open

    %table.table.table-striped.table-condensed
      %tr
        %th Date:
        %td= @order_slip.created_at.strftime("%d %b %y")
      %tr
        %th Order Type:
        %td= @order_slip.order_type
      %tr
        %th Server:
        %td= User.find(@order_slip.user_id).name
      %tr
        %th Status:
        - if @order_slip.open?
          %td Open
        - else
          %td Closed    

  - @total = 0
  .row
    .col-md-12
      = form_tag split_order_slip_path(@order_slip) do
        .panel.panel-default
          .panel-heading Item Details
          %table.table.table-striped.table-condensed
            %tr
              - if @order_slip.open?
                %td
              %th Timestamp
              %th Name
              %th Quantity
              %th Item Price
              %th Total Price
            - @order_slip.order_slip_items.each do |i|
              %tr
                - if @order_slip.open?
                  %td= check_box_tag "selected[]", i.id
                %td= i.created_at.strftime("%I:%M %p")
                %td= Product.find(i.product_id).item_name
                %td= i.quantity
                %td= number_with_precision(Product.find(i.product_id).price, precision: 2)
                - @per_item = (i.quantity * Product.find(i.product_id).price)
                %td= number_with_precision(@per_item, precision: 2)
                - @total = @total + @per_item
            - if (@order_slip.takeout_type == "Box")
              %tr
                %td Takeout Box:
                - if @order_slip.open?
                  %td
                %td
                %td
                %td
                %td 5.00
                -@total = @total + 5
            %tr
              %td Total:
              - if @order_slip.open?
                %td
              %td
              %td
              %td
              %td= number_with_precision(@total, precision: 2)
            - if @order_slip.open?
              %tr
                %td
                  = submit_tag 'Split', class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Split"


- if @order_slip.open?

  .row
    .col-md-12
      .panel.panel-default
        .panel-heading Merge with:
        %table.table.table-condensed
          %tr
            %th
            %th Order Type
            %th Table / Takeout Number
          - OrderSlip.where.not(id: @order_slip.id).each do |tab|
            -if tab.open?
              %tr
                %td
                  = link_to merge_order_slip_path(:another_id=>tab.id), :method => :post, class: "btn btn-primary btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "Merge" do
                    %span.glyphicon.glyphicon-plus-sign            
                %td= tab.order_type
                - if tab.order_type == "Dine-In"
                  %td= tab.table_number
                - elsif tab.order_type == "Takeout"
                  %td= tab.takeout_number