config/routes.rb
Rails.application.routes.draw do

  match 'sales_report' => 'static_pages#sales_report', :via => [:get]
  match 'sales_report_create' => 'static_pages#sales_report_create', :via => [:get]
  match 'daily_sales' => 'static_pages#sales', :via => [:get]
  match 'monthly_sales' => 'static_pages#monthly', :via => [:get]
  match 'dine_in' => 'static_pages#table', :via => [:get]
  match 'takeout' => 'static_pages#takeout', :via => [:get]
  match 'table_one' => 'static_pages#one', :via => [:get]
  match 'table_two' => 'static_pages#two', :via => [:get]
  match 'table_three' => 'static_pages#three', :via => [:get]
  match 'table_four' => 'static_pages#four', :via => [:get]
  match 'table_five' => 'static_pages#five', :via => [:get]
  match 'table_six' => 'static_pages#six', :via => [:get]
  match 'table_seven' => 'static_pages#seven', :via => [:get]

  resources :products
  resources :inventories
  resources :order_slip_items
  resources :order_slips do
    collection do
      get :close
    end
    member do
      post :split
      get :archive
      post :merge
      get :activate
    end

  end

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users do
    collection do
      get 'dashboard'
    end
  end
  authenticated :user do
    root :to => 'users#dashboard', :as => :authenticated_root
  end
  root :to => redirect('/login')

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
-if user_signed_in?
  %nav.navbar.navbar-inverse.navbar-fixed-top
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'Home', root_path, class: 'navbar-brand'
      .collapse.navbar-collapse
        = render 'layouts/navigation_links'
        = render 'layouts/navigation_right'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %ul.nav.navbar-nav
    %li.dropdown
      %a.dropdown-toggle{"href" => '#', "data-toggle" => 'dropdown'}
        Order Management
        %span.caret
      %ul.dropdown-menu{role: 'menu'}
        %li= link_to 'Dine-In', dine_in_path
        %li= link_to 'Takeout', takeout_path
        %li.divider
        %li= link_to 'All', order_slips_path
        %li.divider
        %li= link_to 'Closed', close_order_slips_path
    %li= link_to 'Menu', products_path
    %li= link_to 'Inventory', inventories_path
    %li= link_to 'Sales', sales_report_path
    / %li.dropdown
    /   %a.dropdown-toggle{"href" => '#', "data-toggle" => 'dropdown'}
    /     Sales Report
    /     %span.caret
    /   %ul.dropdown-menu{role: 'menu'}
    /     %li= link_to 'Daily', daily_sales_path
    /     %li= link_to 'Monthly', monthly_sales_path

app/views/layouts/_navigation_right.html.haml
- if user_signed_in?
  %ul.nav.navbar-nav.navbar-right
    %li.dropdown
      %a.dropdown-toggle{"href" => '#', "data-toggle" => 'dropdown'}
        %span.glyphicon.glyphicon-user
        %span.caret
      %ul.dropdown-menu{role: 'menu'}
        %li= link_to 'Edit Profile', edit_user_path(current_user)
        %li= link_to 'Dashboard', dashboard_users_path
        %li.divider
        %li= link_to 'Log Out', destroy_user_session_path, :method=>'delete'
  - if current_user.is_admin?
    %ul.nav.navbar-nav.navbar-right
      %li.dropdown
        %a.dropdown-toggle{"href" => '#', "data-toggle" => 'dropdown'}
          %span.glyphicon.glyphicon-cog
          %span.caret
        %ul.dropdown-menu{role: 'menu'}
          - if can? :manage, User
            %li= link_to 'Users', users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'POSitive'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'POSitive'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      %header
        = render 'layouts/navigation'
      %main{:role => "main"}
        = render 'layouts/messages'
        .row
          .col-md-12
            = yield

= javascript_include_tag :defaults, :cache => true